version: "3.9"
services:
  web:
    build: .
    container_name: "app1_${TENANT}"
    networks:
      - "tenant_network"
    command: yarn start
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://todoapp@postgres/todos
networks:
  tenant_network:
    external:
      name: "network_${TENANT}"
